[2021-07-19 08:52:47,077] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.processing_tasks.task_2 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 08:52:47,245] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.processing_tasks.task_2 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 08:52:47,245] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 08:52:47,245] {taskinstance.py:1088} INFO - Starting attempt 4 of 4
[2021-07-19 08:52:47,245] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 08:52:47,620] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): processing_tasks.task_2> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 08:52:47,623] {standard_task_runner.py:52} INFO - Started process 2099 to run task
[2021-07-19 08:52:47,626] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'processing_tasks.task_2', '2021-07-18T07:54:25.449895+00:00', '--job-id', '96', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmp02mxljef', '--error-file', '/tmp/tmpb1_pg0pk']
[2021-07-19 08:52:47,627] {standard_task_runner.py:77} INFO - Job 96: Subtask processing_tasks.task_2
[2021-07-19 08:52:48,872] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.processing_tasks.task_2 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 08:52:50,431] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=processing_tasks.task_2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 08:52:50,432] {logging_mixin.py:104} INFO - This is task 2 function
[2021-07-19 08:52:51,014] {python.py:151} INFO - Done. Returned value was: None
[2021-07-19 08:52:51,311] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=processing_tasks.task_2, execution_date=20210718T075425, start_date=20210719T085247, end_date=20210719T085251
[2021-07-19 08:52:52,040] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-19 08:52:52,056] {local_task_job.py:151} INFO - Task exited with return code 0
