[2021-07-18 04:39:51,504] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2021-07-16T10:01:41.905293+00:00 [queued]>
[2021-07-18 04:39:51,940] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2021-07-16T10:01:41.905293+00:00 [queued]>
[2021-07-18 04:39:51,940] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 04:39:51,940] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-07-18 04:39:51,940] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 04:39:52,070] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_4> on 2021-07-16T10:01:41.905293+00:00
[2021-07-18 04:39:52,074] {standard_task_runner.py:52} INFO - Started process 1225 to run task
[2021-07-18 04:39:52,079] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2021-07-16T10:01:41.905293+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp376vqb4c', '--error-file', '/tmp/tmpwzvpsl66']
[2021-07-18 04:39:52,080] {standard_task_runner.py:77} INFO - Job 30: Subtask task_4
[2021-07-18 04:39:53,303] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2021-07-16T10:01:41.905293+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-18 04:39:54,804] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-16T10:01:41.905293+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-16T10:01:41.905293+00:00
[2021-07-18 04:39:54,805] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 04:39:54,805] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-18 04:39:54,812] {subprocess.py:75} INFO - Output:
[2021-07-18 04:39:57,817] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-18 04:39:58,654] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20210716T100141, start_date=20210718T043951, end_date=20210718T043958
[2021-07-18 04:39:59,314] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-18 04:39:59,327] {local_task_job.py:151} INFO - Task exited with return code 0
