[2021-07-20 07:13:42,311] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-20 07:13:42,712] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-20 07:13:42,712] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 07:13:42,712] {taskinstance.py:1088} INFO - Starting attempt 11 of 11
[2021-07-20 07:13:42,712] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 07:13:42,842] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_data> on 2021-07-18T07:54:25.449895+00:00
[2021-07-20 07:13:42,845] {standard_task_runner.py:52} INFO - Started process 31549 to run task
[2021-07-20 07:13:42,849] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'save_data', '2021-07-18T07:54:25.449895+00:00', '--job-id', '147', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmpp1m23dbb', '--error-file', '/tmp/tmp7hrmhroe']
[2021-07-20 07:13:42,849] {standard_task_runner.py:77} INFO - Job 147: Subtask save_data
[2021-07-20 07:13:44,115] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.save_data 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-20 07:13:45,687] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=save_data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-20 07:13:46,251] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 07:13:46,539] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=save_data, execution_date=20210718T075425, start_date=20210720T071342, end_date=20210720T071346
[2021-07-20 07:13:47,258] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 07:13:47,278] {local_task_job.py:151} INFO - Task exited with return code 0
