[2021-07-23 12:10:50,764] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-21T00:00:00+00:00 [queued]>
[2021-07-23 12:10:51,151] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-21T00:00:00+00:00 [queued]>
[2021-07-23 12:10:51,151] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-23 12:10:51,152] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-23 12:10:51,152] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-23 12:10:51,278] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): insert_data_to_db> on 2021-07-21T00:00:00+00:00
[2021-07-23 12:10:51,282] {standard_task_runner.py:52} INFO - Started process 855 to run task
[2021-07-23 12:10:51,288] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'insert_data_to_db', '2021-07-21T00:00:00+00:00', '--job-id', '160', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmprrc8e9fh', '--error-file', '/tmp/tmpadqq6b2t']
[2021-07-23 12:10:51,289] {standard_task_runner.py:77} INFO - Job 160: Subtask insert_data_to_db
[2021-07-23 12:10:52,520] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.insert_data_to_db 2021-07-21T00:00:00+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-23 12:10:54,069] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=insert_data_to_db
AIRFLOW_CTX_EXECUTION_DATE=2021-07-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-21T00:00:00+00:00
[2021-07-23 12:10:55,857] {python.py:151} INFO - Done. Returned value was: None
[2021-07-23 12:10:56,146] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=insert_data_to_db, execution_date=20210721T000000, start_date=20210723T121050, end_date=20210723T121056
[2021-07-23 12:10:56,873] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-23 12:10:57,158] {local_task_job.py:151} INFO - Task exited with return code 0
