[2021-07-18 07:50:48,733] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2021-07-17T03:39:23.918881+00:00 [queued]>
[2021-07-18 07:50:48,928] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2021-07-17T03:39:23.918881+00:00 [queued]>
[2021-07-18 07:50:48,929] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 07:50:48,929] {taskinstance.py:1088} INFO - Starting attempt 5 of 5
[2021-07-18 07:50:48,929] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 07:50:49,293] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_4> on 2021-07-17T03:39:23.918881+00:00
[2021-07-18 07:50:49,296] {standard_task_runner.py:52} INFO - Started process 6580 to run task
[2021-07-18 07:50:49,301] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2021-07-17T03:39:23.918881+00:00', '--job-id', '58', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp1cfqhsi1', '--error-file', '/tmp/tmp6_514olk']
[2021-07-18 07:50:49,303] {standard_task_runner.py:77} INFO - Job 58: Subtask task_4
[2021-07-18 07:50:50,513] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2021-07-17T03:39:23.918881+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-18 07:50:52,044] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-17T03:39:23.918881+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-17T03:39:23.918881+00:00
[2021-07-18 07:50:52,047] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 07:50:52,047] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-18 07:50:52,054] {subprocess.py:75} INFO - Output:
[2021-07-18 07:50:55,056] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-18 07:50:55,960] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20210717T033923, start_date=20210718T075048, end_date=20210718T075055
[2021-07-18 07:50:56,666] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-18 07:50:56,676] {local_task_job.py:151} INFO - Task exited with return code 0
