[2021-07-23 12:10:52,311] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-22T00:00:00+00:00 [queued]>
[2021-07-23 12:10:52,704] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-22T00:00:00+00:00 [queued]>
[2021-07-23 12:10:52,705] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-23 12:10:52,705] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-23 12:10:52,705] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-23 12:10:52,846] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): insert_data_to_db> on 2021-07-22T00:00:00+00:00
[2021-07-23 12:10:52,850] {standard_task_runner.py:52} INFO - Started process 872 to run task
[2021-07-23 12:10:52,856] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'insert_data_to_db', '2021-07-22T00:00:00+00:00', '--job-id', '161', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmpf2y5orbr', '--error-file', '/tmp/tmpbpsl1jt8']
[2021-07-23 12:10:52,856] {standard_task_runner.py:77} INFO - Job 161: Subtask insert_data_to_db
[2021-07-23 12:10:54,086] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.insert_data_to_db 2021-07-22T00:00:00+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-23 12:10:55,657] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=insert_data_to_db
AIRFLOW_CTX_EXECUTION_DATE=2021-07-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-22T00:00:00+00:00
[2021-07-23 12:10:57,249] {python.py:151} INFO - Done. Returned value was: None
[2021-07-23 12:10:57,542] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=insert_data_to_db, execution_date=20210722T000000, start_date=20210723T121052, end_date=20210723T121057
[2021-07-23 12:10:58,269] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-23 12:10:58,759] {local_task_job.py:151} INFO - Task exited with return code 0
