[2021-07-18 04:39:33,450] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks.task_2 2021-07-17T03:02:30.080012+00:00 [queued]>
[2021-07-18 04:39:33,829] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks.task_2 2021-07-17T03:02:30.080012+00:00 [queued]>
[2021-07-18 04:39:33,830] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 04:39:33,830] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-07-18 04:39:33,830] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 04:39:33,957] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): processing_tasks.task_2> on 2021-07-17T03:02:30.080012+00:00
[2021-07-18 04:39:33,959] {standard_task_runner.py:52} INFO - Started process 1212 to run task
[2021-07-18 04:39:33,967] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'processing_tasks.task_2', '2021-07-17T03:02:30.080012+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpmhernzyv', '--error-file', '/tmp/tmpzrdcw36k']
[2021-07-18 04:39:33,968] {standard_task_runner.py:77} INFO - Job 26: Subtask processing_tasks.task_2
[2021-07-18 04:39:35,177] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.processing_tasks.task_2 2021-07-17T03:02:30.080012+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-18 04:39:36,743] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=processing_tasks.task_2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-17T03:02:30.080012+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-17T03:02:30.080012+00:00
[2021-07-18 04:39:36,743] {logging_mixin.py:104} INFO - This is task 2 function
[2021-07-18 04:39:37,315] {python.py:151} INFO - Done. Returned value was: None
[2021-07-18 04:39:37,601] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=processing_tasks.task_2, execution_date=20210717T030230, start_date=20210718T043933, end_date=20210718T043937
[2021-07-18 04:39:38,517] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-18 04:39:38,552] {local_task_job.py:151} INFO - Task exited with return code 0
